/**
 * Proof that the web build actually renders — not that it merely compiles.
 *
 * Drives a real Chromium against a served build at a desktop viewport, and fails on anything
 * a user would notice: a console error, an uncaught exception, a failed request, a missing
 * layout, or a route that renders the mobile column instead of the desktop shell.
 *
 * Two passes are needed because the signed-in app cannot be reached in a plain production
 * build — the auth bypass is compiled out by design (see lib/dev-auth.ts):
 *
 *   --mode=landing   production build, signed out  -> expects [data-testid=landing]
 *   --mode=app       development-mode build + bypass -> expects [data-testid=sidebar]
 *
 * Usage:
 *   node scripts/verify-web.mjs --base=http://localhost:4173 --mode=landing --out=../../docs/screenshots/web
 */
import { chromium } from 'playwright-core'
import { mkdir, readdir } from 'node:fs/promises'
import { join } from 'node:path'

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const [k, ...rest] = a.replace(/^--/, '').split('=')
    return [k, rest.join('=') || true]
  }),
)

const BASE = args.base ?? 'http://localhost:4173'
const MODE = args.mode ?? 'app'
const OUT = args.out ?? 'verify-shots'
const VIEWPORT = { width: 1440, height: 900 }

/** Routes to exercise, per mode. */
const ROUTES =
  MODE === 'landing'
    ? [{ name: 'landing', path: '/', expect: '[data-testid="landing"]' }]
    : [
        { name: 'train', path: '/', expect: '[data-testid="sidebar"]' },
        { name: 'category', path: '/category/chest', expect: '[data-testid="sidebar"]' },
        { name: 'planner', path: '/planner', expect: '[data-testid="sidebar"]' },
        { name: 'progress', path: '/progress', expect: '[data-testid="sidebar"]' },
        { name: 'history', path: '/history', expect: '[data-testid="sidebar"]' },
        { name: 'session', path: '/session', expect: '[data-testid="sidebar"]' },
        // Session ids are generated by the seed, so this one is reached the way a user
        // reaches it — open History and click the first row — rather than hardcoding an id.
        {
          name: 'session-detail',
          path: '/history',
          via: '[data-testid="session-row"]',
          expect: '[data-testid="session-detail"]',
        },
      ]

/**
 * Noise that is not a defect and must not fail the run.
 * Kept deliberately tight — a blanket filter would defeat the point of the check.
 */
const IGNORE = [
  /Download the React DevTools/i,
  /\[vite\] connect(ing|ed)/i,
  // the dev bypass announces itself on purpose
  /DEV AUTH BYPASS ACTIVE/i,
  /seeded dev data/i,
]
const ignorable = (t) => IGNORE.some((re) => re.test(t))

async function launch() {
  const cache = process.env.LOCALAPPDATA ? join(process.env.LOCALAPPDATA, 'ms-playwright') : null
  if (cache) {
    try {
      const dirs = (await readdir(cache)).filter((d) => /^chromium-\d+$/.test(d)).sort()
      const newest = dirs.at(-1)
      if (newest) return await chromium.launch({ executablePath: join(cache, newest, 'chrome-win64', 'chrome.exe') })
    } catch {
      /* fall through */
    }
  }
  return await chromium.launch({ channel: 'chrome' })
}

const browser = await launch()
const ctx = await browser.newContext({
  viewport: VIEWPORT,
  deviceScaleFactor: 2,
  colorScheme: 'dark',
  locale: 'en-GB',
  timezoneId: 'Asia/Kolkata',
})

/**
 * A live session, written before any bundle runs, so /session shows the real logging UI
 * rather than its empty state. Weights line up with the seeded 6-week block so the
 * "last time" hints render instead of "first time".
 */
if (MODE === 'app') {
  await ctx.addInitScript(() => {
    const s = {
      categoryKey: 'chest',
      title: 'Chest',
      startedAt: Date.now() - 27 * 60 * 1000,
      exercises: [
        {
          exercise: 'Incline Bench Press',
          sets: [
            { weight: 57.5, reps: 10, done: true },
            { weight: 57.5, reps: 9, done: true },
            { weight: 60, reps: 8, done: false },
          ],
        },
        {
          exercise: 'Flat Bench Press',
          sets: [
            { weight: 72.5, reps: 8, done: true },
            { weight: 75, reps: 6, done: false },
          ],
        },
        { exercise: 'Pec Fly', sets: [{ weight: 30, reps: 12, done: false }] },
      ],
    }
    localStorage.setItem('cfit:active', JSON.stringify(s))
  })
}

await mkdir(OUT, { recursive: true })

const problems = []
const page = await ctx.newPage()

let current = '(startup)'
page.on('console', (m) => {
  if (m.type() !== 'error' && m.type() !== 'warning') return
  const t = m.text()
  if (ignorable(t)) return
  problems.push(`[${current}] console.${m.type()}: ${t}`)
})
page.on('pageerror', (e) => problems.push(`[${current}] pageerror: ${e.message}`))
page.on('requestfailed', (r) => {
  const err = r.failure()?.errorText ?? 'failed'
  if (/ERR_ABORTED/.test(err)) return // navigations we cancelled ourselves
  problems.push(`[${current}] requestfailed: ${r.url()} — ${err}`)
})
page.on('response', (r) => {
  if (r.status() >= 400) problems.push(`[${current}] http ${r.status()}: ${r.url()}`)
})

console.log(`\nverify-web  mode=${MODE}  base=${BASE}  viewport=${VIEWPORT.width}x${VIEWPORT.height}\n`)

/*
 * Boot splash — asserted in the DOM, not by screenshot. On a fast local preview it is gone
 * within a couple of frames, so a capture races it and proves nothing either way. Both halves
 * matter: that it paints before the bundle has run, and that it always clears afterwards.
 */
{
  current = 'boot'
  const boot = await ctx.newPage()
  // 'domcontentloaded', not 'commit': at commit the document may not be parsed yet, so #boot
  // legitimately does not exist and the check fails for the wrong reason. Module scripts are
  // deferred, so the bundle still has not run at this point — the splash is genuinely up.
  await boot.goto(BASE, { waitUntil: 'domcontentloaded', timeout: 45000 })
  const painted = await boot.evaluate(() => {
    const el = document.getElementById('boot')
    if (!el) return { present: false, visible: false }
    const s = getComputedStyle(el)
    return { present: true, visible: s.visibility !== 'hidden' && s.opacity !== '0' }
  })
  if (!painted.present) problems.push('[boot] no #boot splash in the served HTML')
  else if (!painted.visible) problems.push('[boot] #boot present but not visible on first paint')

  await boot
    .waitForFunction(() => document.documentElement.classList.contains('app-ready'), { timeout: 15000 })
    .catch(() => problems.push('[boot] app-ready never applied — the splash would never clear'))
  // app-ready only *starts* the 0.42s fade; visibility stays 'visible' for its duration, so
  // checking immediately reports a false failure. Wait past the transition, then assert.
  await boot.waitForTimeout(700)
  const cleared = await boot.evaluate(() => {
    const el = document.getElementById('boot')
    if (!el) return true
    const s = getComputedStyle(el)
    return s.visibility === 'hidden' || s.opacity === '0'
  })
  if (!cleared) problems.push('[boot] splash still visible after app-ready')
  console.log(`  ok    boot       painted=${painted.visible}  cleared=${cleared}`)
  await boot.close()
}

let failed = 0
for (const r of ROUTES) {
  current = r.name
  try {
    await page.goto(BASE + r.path, { waitUntil: 'networkidle', timeout: 45000 })
    if (r.via) {
      await page.waitForSelector(r.via, { timeout: 20000 })
      await page.locator(r.via).first().click()
    }
    await page.waitForSelector(r.expect, { timeout: 20000, state: 'attached' })
    // the shell must still be there on every signed-in route, including ones reached by click
    if (MODE === 'app') await page.waitForSelector('[data-testid="sidebar"]', { timeout: 10000, state: 'attached' })
    // let entrance animations, rings and charts settle before the capture
    await page.waitForTimeout(1200)
    await page.evaluate(() => document.fonts.ready)

    // A page that mounted but painted nothing is still a failure.
    const text = (await page.locator('body').innerText()).trim()
    if (text.length < 40) {
      problems.push(`[${r.name}] rendered almost no text (${text.length} chars) — page is probably blank`)
    }

    await page.screenshot({ path: join(OUT, `${r.name}.png`), fullPage: false })
    console.log(`  ok    ${r.name.padEnd(10)} ${r.path}`)
  } catch (e) {
    failed++
    console.error(`  FAIL  ${r.name.padEnd(10)} ${r.path}\n        ${e.message.split('\n')[0]}`)
    try {
      await page.screenshot({ path: join(OUT, `${r.name}-FAILED.png`) })
    } catch {
      /* page may be unusable */
    }
  }
}

await browser.close()

if (problems.length) {
  console.error(`\n${problems.length} problem(s):`)
  for (const p of [...new Set(problems)]) console.error(`  ${p}`)
}

const bad = failed + problems.length
if (bad) {
  console.error(`\nFAILED — ${failed} route(s) did not render, ${problems.length} console/network problem(s).`)
  process.exit(1)
}
console.log(`\nPASS — ${ROUTES.length} route(s) rendered at ${VIEWPORT.width}x${VIEWPORT.height}, zero console errors.`)
