import { FEMALE_HERO, FEMALE_EXERCISE_IMAGES } from './femaleAssets'

/**
 * Where the exercise and hero imagery lives.
 *
 * Kept byte-identical between apps/web and apps/mobile — enforced by
 * scripts/check-parity.mjs — so both surfaces resolve the same URL for the same image,
 * and a device that has already downloaded a photo in one never downloads it again in
 * the other.
 *
 * These 35 PNGs are ~30 MB. They used to be bundled into the app builds, so every user
 * paid the full 30 MB on first install AND on every update, forever, whether or not they
 * ever opened the exercise. Serving them from a Cloudflare static-assets Worker means a
 * device downloads an image at most once in its lifetime:
 *
 *   - the CDN marks them `immutable` for a year (see cdn/public/_headers)
 *   - the web build keeps them in Cache Storage via a CacheFirst service worker rule
 *   - React Native keeps them on disk via expo-image's `memory-disk` cache policy
 *
 * The last two matter more than the HTTP header: Cache Storage and the expo-image disk cache
 * are keyed by URL and live in app storage, so they survive an app update. An HTTP cache alone
 * would not reliably do that.
 *
 * The filenames are effectively content-addressed — a photo keeps its name for life, and a
 * changed photo ships under a NEW name. Never overwrite one in place: devices holding the old
 * copy would keep serving it for a year.
 *
 * Changing ASSET_CDN is a breaking change for every device already in the field — they
 * re-download the whole library once. It must be changed together with the `urlPattern`
 * origin check in apps/web/vite.config.ts, or images still load but the service worker
 * silently stops caching them.
 *
 * ## The female variant
 *
 * A second, deliberately partial tree lives alongside the one above, under `/female/` —
 * a whole gendered copy rather than a per-file variant, for the same reason a changed
 * photo ships under a new filename instead of overwriting the old one: devices holding
 * the male copy of `shrugs.png` must keep getting the male copy forever, so the female
 * photo needs its own path, not the same one with different bytes behind it.
 *
 * It grows over time (see cdn/README.md and docs/IMAGES.md for how the base library is
 * maintained) and `src/data/femaleAssets.ts` — regenerated by
 * `apps/web/scripts/gen-female-assets.mjs` from whatever actually exists under
 * `cdn/public/female/` — is the honest record of what's there right now. `cdnExercise`
 * and `cdnHero` check it themselves and fall back to the male URL for anything not yet
 * shot, so a caller never has to know the set is incomplete: passing `'female'` either
 * gets the female photo or the male one, never a 404.
 */
export const ASSET_CDN = 'https://cdn.grindz.dev'

export type Gender = 'male' | 'female'

/**
 * Public URL for an exercise photo, e.g. ('shoulders', 'shrugs.png', 'female').
 * `gender` defaults to 'male' so every pre-existing call site is unchanged.
 */
export function cdnExercise(categoryKey: string, img: string, gender: Gender = 'male'): string {
  if (gender === 'female' && FEMALE_EXERCISE_IMAGES.has(`${categoryKey}/${img}`)) {
    return `${ASSET_CDN}/female/images/${categoryKey}/${img}`
  }
  return `${ASSET_CDN}/images/${categoryKey}/${img}`
}

/**
 * Public URL for a category hero image. Falls back the same way as cdnExercise.
 *
 * The female side reads its filename out of FEMALE_HERO rather than composing
 * `${categoryKey}.png`, because a hero is the one image whose name is derived from data
 * and so cannot be reshot under a free-form new name. A replacement ships numbered —
 * `cardio-2.png` — and the manifest points at the newest, which keeps the "never overwrite
 * an image in place" rule intact for a file the URL scheme would otherwise force us to
 * mutate. The male tree has no replacements yet and stays on the derived name.
 */
export function cdnHero(categoryKey: string, gender: Gender = 'male'): string {
  const female = gender === 'female' ? FEMALE_HERO.get(categoryKey) : undefined
  if (female) return `${ASSET_CDN}/female/hero/${female}`
  return `${ASSET_CDN}/hero/${categoryKey}.png`
}
