// AUTO-GENERATED by scripts/gen-female-assets.mjs from cdn/public/female/ — DO NOT EDIT BY HAND.
// Regenerate after adding or removing a file under that directory, then commit the result.
// See that script's header comment for why this is a committed manifest rather than a
// runtime directory listing (the CDN is a static-assets Worker with no listing API).

/**
 * Category key -> the file serving its female hero, e.g.
 * 'chest' -> cdn/public/female/hero/chest.png.
 *
 * A filename rather than a bare key because a replaced hero ships under a numbered name
 * ('cardio-2.png') instead of overwriting the old one — the CDN serves these immutably for
 * a year, so mutating a file in place would leave every device that already has it showing
 * the old photo. Only the newest number per category appears here.
 */
export const FEMALE_HERO: ReadonlyMap<string, string> = new Map([
  ['abs', 'abs.png'],
  ['back', 'back.png'],
  ['biceps', 'biceps.png'],
  ['cardio', 'cardio-2.png'],
  ['chest', 'chest.png'],
  ['legs', 'legs.png'],
  ['shoulders', 'shoulders.png'],
  ['triceps', 'triceps.png'],
])

/** '<category>/<file>.png' pairs that exist under cdn/public/female/images/. */
export const FEMALE_EXERCISE_IMAGES: ReadonlySet<string> = new Set([
  'abs/bicycle-crunches.png',
  'abs/crunches.png',
  'abs/leg-raises.png',
  'abs/mountain-climbers.png',
  'abs/plank-shoulder-tap.png',
  'abs/seated-knee-tucks.png',
  'back/dumbbell-row.png',
  'back/lat-pulldown.png',
  'back/seated-cable-row.png',
  'back/t-bar-rows.png',
  'biceps/concentration-curl.png',
  'biceps/preacher-curl.png',
  'biceps/rope-hammer-curl.png',
  'biceps/wrist-curls.png',
  'cardio/elliptical.png',
  'chest/decline-bench-press.png',
  'chest/flat-bench-press.png',
  'chest/incline-bench-press.png',
  'chest/pec-fly.png',
  'legs/adductor-and-abductor.png',
  'legs/barbell-squats.png',
  'legs/dumbbell-romanian-deadlift.png',
  'legs/nordic-hamstring-curl.png',
  'legs/pistol-squat.png',
  'legs/seated-calf-raise-machine.png',
  'legs/seated-leg-curl.png',
  'legs/seated-leg-extension.png',
  'shoulders/dumbbell-front-raise.png',
  'shoulders/dumbbell-lateral-raise.png',
  'shoulders/overhead-shoulder-press.png',
  'shoulders/reverse-pec-deck.png',
  'shoulders/rope-face-pull.png',
  'shoulders/shrugs.png',
  'shoulders/upright-row.png',
  'triceps/cable-pushdowns.png',
  'triceps/overhead-cable-triceps-extension.png',
  'triceps/seated-overhead-dumbbell-triceps-extension.png',
])
