// AUTO-GENERATED by scripts/gen-female-assets.mjs from cdn/public/female/ — DO NOT EDIT BY HAND.
// Regenerate after adding or removing a file under that directory, then commit the result.
// See that script's header comment for why this is a committed manifest rather than a
// runtime directory listing (the CDN is a static-assets Worker with no listing API).

/** Category keys with a female hero image, e.g. 'chest' -> cdn/public/female/hero/chest.png */
export const FEMALE_HERO: ReadonlySet<string> = new Set([
  'abs',
  'back',
  'biceps',
  'cardio',
  'chest',
  'legs',
  'shoulders',
  'triceps',
])

/** '<category>/<file>.png' pairs that exist under cdn/public/female/images/. */
export const FEMALE_EXERCISE_IMAGES: ReadonlySet<string> = new Set([
  'back/dumbbell-row.png',
  'back/lat-pulldown.png',
  'back/seated-cable-row.png',
  'back/t-bar-rows.png',
  'biceps/concentration-curl.png',
  'biceps/preacher-curl.png',
  'biceps/rope-hammer-curl.png',
  'biceps/wrist-curls.png',
  'cardio/cardio.png',
  'chest/decline-bench-press.png',
  'chest/flat-bench-press.png',
  'chest/incline-bench-press.png',
  'chest/pec-fly.png',
  'legs/adductor-and-abductor.png',
  'legs/barbell-squats.png',
  'legs/dumbbell-romanian-deadlift.png',
  'legs/seated-calf-raise-machine.png',
  'legs/seated-leg-curl.png',
  'legs/seated-leg-extension.png',
  'triceps/cable-pushdowns.png',
  'triceps/overhead-cable-triceps-extension.png',
  'triceps/seated-overhead-dumbbell-triceps-extension.png',
])
