/**
 * Pulls the exercise catalog from the CDN at runtime, instead of waiting for it to reach a
 * device inside a new APK.
 *
 * The image half of this problem was already solved — see docs/IMAGES.md — by fetching
 * photos from `cdn.grindz.dev` instead of bundling them. This is the same move for the *row*
 * describing an exercise: its name, form cue, tips, which muscles it lights up, and whether
 * it has a female photo. Those are plain data, generated onto the same CDN by
 * `apps/web/scripts/gen-catalog-json.mts` from the same `catalog.ts` / `exerciseMuscles.ts` a
 * developer already edits — so "add a workout on GitHub" is still just editing those two
 * files; this is what gets it in front of a user without them reinstalling anything.
 *
 * That last item was a gap worth naming: the first version of this payload carried the row
 * but not `femaleAssets.ts`, so a new exercise arrived complete except that a user on the
 * female body type saw the male photo — the manifest answering "is there a female shot of
 * this?" was still the one compiled into the APK. Anything the resolver consults to build an
 * image URL has to travel with the row, or the row is only half-delivered.
 *
 * Two calls, both wired up in `lib/app-context.tsx`:
 *   - `hydrateCatalogFromCache()` — fast, on every app open, from AsyncStorage. This is what
 *     makes a previously-synced exercise available offline, not just the bundled ones.
 *   - `syncCatalogFromNetwork()` — slower, checks the CDN for something newer and persists it
 *     if so.
 *
 * Every step here fails soft, matching the upload pipeline in lib/storage.ts: a bad response,
 * a network error, a malformed payload — all of them just mean "keep whatever the app
 * already has" (the bundled fallback, or the last cache that DID validate). Never throws,
 * never surfaces an error to the UI. A stale exercise list is a much smaller problem than a
 * broken one.
 */
import AsyncStorage from '@react-native-async-storage/async-storage'
import type { Category } from '../lib/types'
import { applyLiveCatalog } from './catalog'
import { applyLiveMuscles, type MuscleWork } from './exerciseMuscles'
import { applyLiveFemaleAssets } from './femaleAssets'

const CATALOG_URL = 'https://cdn.grindz.dev/catalog.json'
const STORAGE_KEY = 'grindz.catalog.v1'

interface CatalogPayload {
  version: string
  categories: Category[]
  tips: Record<string, string[]>
  muscles: Record<string, MuscleWork>
  /*
   * Which exercises and categories have a female photo on the CDN — the same manifest
   * `femaleAssets.ts` holds, sent as data so it is not frozen at build time.
   *
   * Optional, and deliberately so in both directions. Backwards: a payload generated before
   * these existed (or cached on disk from one) simply leaves the bundled manifest alone
   * rather than clearing it — the exercises it covers are exactly the ones the APK already
   * knows about. Forwards: an app version older than this field ignores it, which is the
   * whole reason the catalogue is fetched as plain data rather than as code.
   */
  femaleHero?: [string, string][]
  femaleImages?: string[]
}

/**
 * Structural check only, not a deep schema validation. The payload is generated by our own
 * script from our own typed source, so the realistic failure modes are "request didn't
 * return JSON" or "an old client talking to a shape from a future version" — both of which
 * this catches. A hand-corrupted `catalog.json` getting past this and rendering oddly is not
 * a case worth building a full validator for.
 */
function isValidPayload(x: unknown): x is CatalogPayload {
  if (!x || typeof x !== 'object') return false
  const p = x as Record<string, unknown>
  return (
    typeof p.version === 'string' &&
    Array.isArray(p.categories) &&
    typeof p.tips === 'object' && p.tips !== null &&
    typeof p.muscles === 'object' && p.muscles !== null
  )
}

// guards against re-applying (and re-rendering for) a payload the app already has, whether
// it came from the cache first and the network confirmed the same version, or vice versa
let lastAppliedVersion: string | null = null

/** Every entry has to be the right shape, or the bundled manifest is left alone entirely — a half-applied one would resolve some photos to a 404. */
function isStringPairs(x: unknown): x is [string, string][] {
  return Array.isArray(x) && x.every((p) => Array.isArray(p) && p.length === 2 && typeof p[0] === 'string' && typeof p[1] === 'string')
}

function apply(payload: CatalogPayload): boolean {
  if (payload.version === lastAppliedVersion) return false
  applyLiveCatalog(payload.categories, payload.tips)
  applyLiveMuscles(payload.muscles)
  // Absent on a payload older than this field — keep whatever the APK bundled rather than
  // replacing it with an empty set, which would drop every female photo the app already had.
  if (isStringPairs(payload.femaleHero) && Array.isArray(payload.femaleImages) && payload.femaleImages.every((s) => typeof s === 'string')) {
    applyLiveFemaleAssets(new Map(payload.femaleHero), new Set(payload.femaleImages))
  }
  lastAppliedVersion = payload.version
  return true
}

/** Whatever the last successful network sync produced, straight from disk. Returns whether it changed anything (so the caller knows whether a re-render is worth triggering). */
export async function hydrateCatalogFromCache(): Promise<boolean> {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY)
    if (!raw) return false
    const payload = JSON.parse(raw)
    return isValidPayload(payload) && apply(payload)
  } catch {
    // corrupt cache entry — the bundled catalog is still there underneath it
    return false
  }
}

/** Checks the CDN for a fresher catalog and persists it if there is one. */
export async function syncCatalogFromNetwork(): Promise<boolean> {
  try {
    const res = await fetch(CATALOG_URL)
    if (!res.ok) return false
    const payload = await res.json()
    if (!isValidPayload(payload)) return false
    const changed = apply(payload)
    if (changed) await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(payload))
    return changed
  } catch {
    // offline, DNS hiccup, whatever — the app carries on with what it already has
    return false
  }
}
